name: Deploy on Push

on:
  push:
    branches:
      - EXP

jobs:
  build:
    runs-on: self-hosted  # Run on your self-hosted runner connected to EC2 instance

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      # Example deployment using a script on the EC2 instance
      - name: Deploy to EC2 Instance
        if: success()  # Deploy only if previous steps succeed
        run: |
          cd /EXP
          git pull origin EXP  # Update code from the EXP branch
          npm install          # Install dependencies
          npm run build        # Build your application
          pm2 restart /EXP/Web-dev-learning/backend # Restart your application using PM2 or another process manager
